[package]
authors = ["Pascal Hertleif <killercup@gmail.com>"]
name = "handlebars-helpers"
version = "0.1.0"
readme = "README.md"

[dependencies]
handlebars = { git = "https://github.com/sunng87/handlebars-rust.git" }
serde_json = "1.0.3"
